default: &default
  adapter: postgresql
  encoding: unicode
  user: localhost
  password: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookmnanon_dev

test:
  <<: *default
  database: bookmanon_test

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
